In [18]:
#drop na from training dataset, (482697, 150)
train = ML_train.dropna(how='any',axis=0)

In [19]:
#create target1, target2 variables, (482697,)
target1_train = train['target1']
target2_train = train['target2']

In [20]:
#drop target1 target 2 (482697, 148)
train_dp= train.drop('target1', axis = 1)
train_dp= train_dp.drop('target2', axis = 1)

In [7]:
from sklearn.model_selection import train_test_split
train_split, train_hold= train_test_split(ML_train, test_size = 0.5,random_state = 7515)

In [8]:
train_split

,A1,A2,A3,A4,A5,A6,B1,B2,B3,B4,...,Y3,Y4,Y5,Z1,Z2,Z3,Z4,Z5,target1,target2
45752,-0.598498,0.730697,0.731210,0.736883,0.057931,-1.228050,-0.531244,0.719970,0.728279,0.732755,...,0.727106,-0.088237,0.539174,0.733671,1.388115,0.727442,-0.068705,1.048750,0,0
478875,-0.751546,0.307621,0.308729,0.316340,0.065057,-0.614003,-0.003584,0.312481,0.307257,0.307965,...,0.306272,0.077100,-0.020718,0.308472,-1.429768,0.300659,0.077776,0.596054,0,0
56926,0.641306,-0.055540,-0.038736,-0.033974,0.806979,0.491283,-0.312745,-0.067272,-0.040149,-0.042213,...,-0.041606,0.277622,-0.103664,-0.040382,-0.020826,-0.047417,0.813866,-0.233888,0,0
128982,-0.512918,-0.125840,-0.126117,-0.137168,-0.528170,0.859711,-1.015296,-0.107795,-0.126743,-0.132076,...,-0.145886,-0.061017,0.062229,-0.128589,-1.429768,-0.127647,-0.432860,0.482880,0,0
153918,0.161416,-0.095877,-0.093555,-0.105235,-0.128462,-0.245574,-0.312093,-0.072211,-0.092344,-0.095389,...,-0.091479,0.482758,-0.041454,-0.097526,0.683644,-0.097612,0.184252,0.143358,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178049,0.068840,-0.202746,-0.195775,-0.194673,0.350957,-0.614003,-0.799797,-0.205699,-0.189567,-0.195145,...,-0.177624,0.738437,0.082966,-0.203103,-0.020826,-0.185248,0.505298,-0.158439,0,0
413243,-0.213092,-0.065329,-0.068412,-0.071154,-0.022836,-0.491193,-0.604947,-0.069863,-0.068450,-0.068182,...,-0.072107,-0.036780,0.228123,-0.071953,-1.429768,-0.073749,-0.043799,-0.045265,0,0
114307,-0.292232,-1.222261,-1.226422,-1.224135,-0.159499,-0.736812,0.340784,-1.224552,-1.227709,-1.227748,...,-1.222907,-0.342048,0.165913,-1.224490,0.683644,-1.224538,-0.194472,-0.384786,1,0
330138,-0.487992,-0.066789,-0.041209,-0.036040,1.370614,0.368473,-0.436683,-0.083907,-0.042085,-0.040976,...,-0.045315,0.534515,0.082966,-0.042464,-0.725297,-0.048240,1.311410,-0.875206,0,0
145153,-0.404575,0.338190,0.336427,0.340301,-0.069223,0.614092,0.167302,0.320592,0.334652,0.337439,...,0.331003,0.006300,-0.456189,0.335838,1.388115,0.328636,-0.125007,-0.045265,0,1

In [21]:
#maximum cluster of 100
cluster = VarClusHi(train_dp,maxclus=100)
cluster.varclus()

In [22]:
cluster.info

   Cluster N_Vars    Eigval1   Eigval2   VarProp
0        0     27  25.207937  0.939543  0.933627
1        1     15  12.183795  0.715847  0.812253
2        2      8   4.258075  0.821469  0.532259
3        3     10   7.855684  0.994001  0.785568
4        4      5   3.708334  0.760334  0.741667
5        5      7   4.562827  0.930051  0.651832
6        6      4   2.836229  0.982385  0.709057
7        7      6   4.491618  0.995408  0.748603
8        8      8   4.304909  0.859996  0.538114
9        9      4   3.049812  0.746286  0.762453
10      10      3   1.852600  0.999241  0.617533
11      11      6   3.273903  0.789935  0.545651
12      12      3   1.625186  0.840002  0.541729
13      13      6   4.983657  0.469072  0.830610
14      14      2   1.537184  0.462816  0.768592
15      15      5   4.015166  0.421516  0.803033
16      16      2   1.451894  0.548106  0.725947
17      17      2   1.406632  0.593368  0.703316
18      18      2   1.355362  0.644638  0.677681
19      19      2   1.182700  0.817300  0.591350
20      20      3   1.296975  0.999983  0.432325
21      21      2   1.113610  0.886390  0.556805
22      22      3   1.972885  0.997534  0.657628
23      23      2   1.141496  0.858504  0.570748
24      24      1   1.000000  0.000000  1.000000
25      25      1   1.000000  0.000000  1.000000
26      26      1   1.000000  0.000000  1.000000
27      27      2   1.028621  0.971379  0.514310
28      28      1   1.000000  0.000000  1.000000
29      29      4   2.525181  0.742912  0.631295
30      30      1   1.000000  0.000000  1.000000

In [23]:
#sort by rs_ratio 
vc = cluster.rsquare.sort_values(['Cluster','RS_Ratio'])

In [1]:
#getting the first variable from each cluster
vc.groupby('Cluster').head(1)['Variable']

NameError: name 'vc' is not defined